backend test:
  image: maven:3-openjdk-11
  stage: test
  script:
    - cd backend/
    - mvn -version
    - mvn test
    - awk -F,
      '{ instructions += $4 + $5; covered += $5 } END
       { print covered, "/", instructions, " instructions covered";
       printf "%.2f%% covered", 100*covered/instructions }'
      target/site/jacoco/jacoco.csv
    - mvn spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.arguments=--ci=yes
# workaround because GitLab doesn't always wait for logs (should be fixed with GitLab runner 13.1)
# https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/2101
    - sleep 10

frontend test:
  image: node:12-alpine
  stage: test
  script:
    - cd frontend/
    - npm ci
    - npx ng build --prod

