backend test:
  image: maven:3-openjdk-11
  stage: test
  script:
    - cd backend/
    - mvn -version
    - mvn test
    - awk -F,
      '{ instructions += $4 + $5; covered += $5 } END
       { print covered, "/", instructions, " instructions covered";
       printf "%.2f%% covered", 100*covered/instructions }'
      target/site/jacoco/jacoco.csv

frontend test:
  image: node:12-alpine
  stage: test
  script:
    - cd frontend/
    - npm ci
    - npx ng build --prod

