logging:
  file.name: ./log/backend.log
  level:
    root: INFO

spring:
  liquibase:
    enabled: true
    changeLog: classpath:/db/migration/db.changelog-master.xml
  datasource:
    url: jdbc:h2:file:./database/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    hibernate:
      ddl-auto: none
    # Allows to fetch lazy properties outside of the original transaction. Although this sounds helpful, the property
    # is disabled since it breaks the principle of least astonishment and leads to bad performance. The learn more,
    # follow this link: https://bit.ly/2LaX9ku
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        page-parameter: offset
        size-parameter: limit
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: removed
            client-secret: removed
          google:
            client-id: removed
            client-secret: removed
          gitlab:
            client-name: GitLab
            scope: openid
            client-id: removed
            client-secret: removed
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/oauth/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys

server:
  tomcat:
    max-swallow-size: -1

cawi:
  jwt-secret: 72d76704e150c907dc05bb7f3dd96f5f2a10479ac54e6961bb7423a89243367d
  # 12 hours in milliseconds
  jwt-expiration-time: 43200000
  image-saved-path: ./images
  image-served-path: /images
  frontend-success-url: http://localhost:4200/login?success
