logging:
  file.name: ./log/backend.log
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:file:./database/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    hibernate:
      ddl-auto: update
    # Allows to fetch lazy properties outside of the original transaction. Although this sounds helpful, the property
    # is disabled since it breaks the principle of least astonishment and leads to bad performance. The learn more,
    # follow this link: https://bit.ly/2LaX9ku
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: removed
            client-secret: removed
          google:
            client_id: "removed"
            client_secret: "removed"
